/*
 * Radarr
 * The way users should interact with Radarr programatically. To utilize any of these endpoints you will need a few pieces of information:  ex: localhost:7878/api/v3/movies?apiKey={key_here}  * url: localhost, 10.1.0.1, 192.168.1.1, etc * port: 7878 (unless you modify it) * apiKey: Located in Settings > General > Security
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.codemakers.radarr4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2001Changes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-08-12T01:48:34.579+02:00[Europe/Berlin]")
public class InlineResponse2001Changes {
  @SerializedName("new")
  private List<String> _new = null;

  @SerializedName("fixed")
  private List<String> fixed = null;

  public InlineResponse2001Changes _new(List<String> _new) {
    this._new = _new;
    return this;
  }

  public InlineResponse2001Changes addNewItem(String _newItem) {
    if (this._new == null) {
      this._new = new ArrayList<>();
    }
    this._new.add(_newItem);
    return this;
  }

   /**
   * Get _new
   * @return _new
  **/
  @Schema(description = "")
  public List<String> getNew() {
    return _new;
  }

  public void setNew(List<String> _new) {
    this._new = _new;
  }

  public InlineResponse2001Changes fixed(List<String> fixed) {
    this.fixed = fixed;
    return this;
  }

  public InlineResponse2001Changes addFixedItem(String fixedItem) {
    if (this.fixed == null) {
      this.fixed = new ArrayList<>();
    }
    this.fixed.add(fixedItem);
    return this;
  }

   /**
   * Get fixed
   * @return fixed
  **/
  @Schema(description = "")
  public List<String> getFixed() {
    return fixed;
  }

  public void setFixed(List<String> fixed) {
    this.fixed = fixed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Changes inlineResponse2001Changes = (InlineResponse2001Changes) o;
    return Objects.equals(this._new, inlineResponse2001Changes._new) &&
        Objects.equals(this.fixed, inlineResponse2001Changes.fixed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_new, fixed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Changes {\n");
    
    sb.append("    _new: ").append(toIndentedString(_new)).append("\n");
    sb.append("    fixed: ").append(toIndentedString(fixed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
