/*
 * Radarr
 * The way users should interact with Radarr programatically. To utilize any of these endpoints you will need a few pieces of information:  ex: localhost:7878/api/v3/movies?apiKey={key_here}  * url: localhost, 10.1.0.1, 192.168.1.1, etc * port: 7878 (unless you modify it) * apiKey: Located in Settings > General > Security
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.codemakers.radarr4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.codemakers.radarr4j.model.CustomFormat;
import de.codemakers.radarr4j.model.Quality;
import de.codemakers.radarr4j.model.QueuedetailsLanguages;
import de.codemakers.radarr4j.model.QueuedetailsStatusMessages;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2009
 */

public class InlineResponse2009 {
  @SerializedName("languages")
  private List<QueuedetailsLanguages> languages = new ArrayList<>();

  @SerializedName("quality")
  private Quality quality = null;

  @SerializedName("customFormats")
  private List<CustomFormat> customFormats = new ArrayList<>();

  @SerializedName("size")
  private BigDecimal size = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("sizeleft")
  private BigDecimal sizeleft = null;

  @SerializedName("timeleft")
  private String timeleft = null;

  @SerializedName("estimatedCompletionTime")
  private String estimatedCompletionTime = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("trackedDownloadStatus")
  private String trackedDownloadStatus = null;

  @SerializedName("trackedDownloadState")
  private String trackedDownloadState = null;

  @SerializedName("statusMessages")
  private List<QueuedetailsStatusMessages> statusMessages = new ArrayList<>();

  @SerializedName("errorMessage")
  private String errorMessage = null;

  @SerializedName("downloadId")
  private String downloadId = null;

  @SerializedName("protocol")
  private String protocol = null;

  @SerializedName("downloadClient")
  private String downloadClient = null;

  @SerializedName("indexer")
  private String indexer = null;

  @SerializedName("outputPath")
  private String outputPath = null;

  @SerializedName("id")
  private Integer id = null;

  public InlineResponse2009 languages(List<QueuedetailsLanguages> languages) {
    this.languages = languages;
    return this;
  }

  public InlineResponse2009 addLanguagesItem(QueuedetailsLanguages languagesItem) {
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * Get languages
   * @return languages
  **/
  @Schema(required = true, description = "")
  public List<QueuedetailsLanguages> getLanguages() {
    return languages;
  }

  public void setLanguages(List<QueuedetailsLanguages> languages) {
    this.languages = languages;
  }

  public InlineResponse2009 quality(Quality quality) {
    this.quality = quality;
    return this;
  }

   /**
   * Get quality
   * @return quality
  **/
  @Schema(required = true, description = "")
  public Quality getQuality() {
    return quality;
  }

  public void setQuality(Quality quality) {
    this.quality = quality;
  }

  public InlineResponse2009 customFormats(List<CustomFormat> customFormats) {
    this.customFormats = customFormats;
    return this;
  }

  public InlineResponse2009 addCustomFormatsItem(CustomFormat customFormatsItem) {
    this.customFormats.add(customFormatsItem);
    return this;
  }

   /**
   * Get customFormats
   * @return customFormats
  **/
  @Schema(required = true, description = "")
  public List<CustomFormat> getCustomFormats() {
    return customFormats;
  }

  public void setCustomFormats(List<CustomFormat> customFormats) {
    this.customFormats = customFormats;
  }

  public InlineResponse2009 size(BigDecimal size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSize() {
    return size;
  }

  public void setSize(BigDecimal size) {
    this.size = size;
  }

  public InlineResponse2009 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(required = true, description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InlineResponse2009 sizeleft(BigDecimal sizeleft) {
    this.sizeleft = sizeleft;
    return this;
  }

   /**
   * Get sizeleft
   * @return sizeleft
  **/
  @Schema(required = true, description = "")
  public BigDecimal getSizeleft() {
    return sizeleft;
  }

  public void setSizeleft(BigDecimal sizeleft) {
    this.sizeleft = sizeleft;
  }

  public InlineResponse2009 timeleft(String timeleft) {
    this.timeleft = timeleft;
    return this;
  }

   /**
   * Get timeleft
   * @return timeleft
  **/
  @Schema(required = true, description = "")
  public String getTimeleft() {
    return timeleft;
  }

  public void setTimeleft(String timeleft) {
    this.timeleft = timeleft;
  }

  public InlineResponse2009 estimatedCompletionTime(String estimatedCompletionTime) {
    this.estimatedCompletionTime = estimatedCompletionTime;
    return this;
  }

   /**
   * Get estimatedCompletionTime
   * @return estimatedCompletionTime
  **/
  @Schema(required = true, description = "")
  public String getEstimatedCompletionTime() {
    return estimatedCompletionTime;
  }

  public void setEstimatedCompletionTime(String estimatedCompletionTime) {
    this.estimatedCompletionTime = estimatedCompletionTime;
  }

  public InlineResponse2009 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InlineResponse2009 trackedDownloadStatus(String trackedDownloadStatus) {
    this.trackedDownloadStatus = trackedDownloadStatus;
    return this;
  }

   /**
   * Get trackedDownloadStatus
   * @return trackedDownloadStatus
  **/
  @Schema(required = true, description = "")
  public String getTrackedDownloadStatus() {
    return trackedDownloadStatus;
  }

  public void setTrackedDownloadStatus(String trackedDownloadStatus) {
    this.trackedDownloadStatus = trackedDownloadStatus;
  }

  public InlineResponse2009 trackedDownloadState(String trackedDownloadState) {
    this.trackedDownloadState = trackedDownloadState;
    return this;
  }

   /**
   * Get trackedDownloadState
   * @return trackedDownloadState
  **/
  @Schema(required = true, description = "")
  public String getTrackedDownloadState() {
    return trackedDownloadState;
  }

  public void setTrackedDownloadState(String trackedDownloadState) {
    this.trackedDownloadState = trackedDownloadState;
  }

  public InlineResponse2009 statusMessages(List<QueuedetailsStatusMessages> statusMessages) {
    this.statusMessages = statusMessages;
    return this;
  }

  public InlineResponse2009 addStatusMessagesItem(QueuedetailsStatusMessages statusMessagesItem) {
    this.statusMessages.add(statusMessagesItem);
    return this;
  }

   /**
   * Get statusMessages
   * @return statusMessages
  **/
  @Schema(required = true, description = "")
  public List<QueuedetailsStatusMessages> getStatusMessages() {
    return statusMessages;
  }

  public void setStatusMessages(List<QueuedetailsStatusMessages> statusMessages) {
    this.statusMessages = statusMessages;
  }

  public InlineResponse2009 errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @Schema(required = true, description = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public InlineResponse2009 downloadId(String downloadId) {
    this.downloadId = downloadId;
    return this;
  }

   /**
   * Get downloadId
   * @return downloadId
  **/
  @Schema(required = true, description = "")
  public String getDownloadId() {
    return downloadId;
  }

  public void setDownloadId(String downloadId) {
    this.downloadId = downloadId;
  }

  public InlineResponse2009 protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @Schema(required = true, description = "")
  public String getProtocol() {
    return protocol;
  }

  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }

  public InlineResponse2009 downloadClient(String downloadClient) {
    this.downloadClient = downloadClient;
    return this;
  }

   /**
   * Get downloadClient
   * @return downloadClient
  **/
  @Schema(required = true, description = "")
  public String getDownloadClient() {
    return downloadClient;
  }

  public void setDownloadClient(String downloadClient) {
    this.downloadClient = downloadClient;
  }

  public InlineResponse2009 indexer(String indexer) {
    this.indexer = indexer;
    return this;
  }

   /**
   * Get indexer
   * @return indexer
  **/
  @Schema(required = true, description = "")
  public String getIndexer() {
    return indexer;
  }

  public void setIndexer(String indexer) {
    this.indexer = indexer;
  }

  public InlineResponse2009 outputPath(String outputPath) {
    this.outputPath = outputPath;
    return this;
  }

   /**
   * Get outputPath
   * @return outputPath
  **/
  @Schema(required = true, description = "")
  public String getOutputPath() {
    return outputPath;
  }

  public void setOutputPath(String outputPath) {
    this.outputPath = outputPath;
  }

  public InlineResponse2009 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2009 inlineResponse2009 = (InlineResponse2009) o;
    return Objects.equals(this.languages, inlineResponse2009.languages) &&
        Objects.equals(this.quality, inlineResponse2009.quality) &&
        Objects.equals(this.customFormats, inlineResponse2009.customFormats) &&
        Objects.equals(this.size, inlineResponse2009.size) &&
        Objects.equals(this.title, inlineResponse2009.title) &&
        Objects.equals(this.sizeleft, inlineResponse2009.sizeleft) &&
        Objects.equals(this.timeleft, inlineResponse2009.timeleft) &&
        Objects.equals(this.estimatedCompletionTime, inlineResponse2009.estimatedCompletionTime) &&
        Objects.equals(this.status, inlineResponse2009.status) &&
        Objects.equals(this.trackedDownloadStatus, inlineResponse2009.trackedDownloadStatus) &&
        Objects.equals(this.trackedDownloadState, inlineResponse2009.trackedDownloadState) &&
        Objects.equals(this.statusMessages, inlineResponse2009.statusMessages) &&
        Objects.equals(this.errorMessage, inlineResponse2009.errorMessage) &&
        Objects.equals(this.downloadId, inlineResponse2009.downloadId) &&
        Objects.equals(this.protocol, inlineResponse2009.protocol) &&
        Objects.equals(this.downloadClient, inlineResponse2009.downloadClient) &&
        Objects.equals(this.indexer, inlineResponse2009.indexer) &&
        Objects.equals(this.outputPath, inlineResponse2009.outputPath) &&
        Objects.equals(this.id, inlineResponse2009.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(languages, quality, customFormats, size, title, sizeleft, timeleft, estimatedCompletionTime, status, trackedDownloadStatus, trackedDownloadState, statusMessages, errorMessage, downloadId, protocol, downloadClient, indexer, outputPath, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2009 {\n");
    
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    customFormats: ").append(toIndentedString(customFormats)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    sizeleft: ").append(toIndentedString(sizeleft)).append("\n");
    sb.append("    timeleft: ").append(toIndentedString(timeleft)).append("\n");
    sb.append("    estimatedCompletionTime: ").append(toIndentedString(estimatedCompletionTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    trackedDownloadStatus: ").append(toIndentedString(trackedDownloadStatus)).append("\n");
    sb.append("    trackedDownloadState: ").append(toIndentedString(trackedDownloadState)).append("\n");
    sb.append("    statusMessages: ").append(toIndentedString(statusMessages)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    downloadId: ").append(toIndentedString(downloadId)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    downloadClient: ").append(toIndentedString(downloadClient)).append("\n");
    sb.append("    indexer: ").append(toIndentedString(indexer)).append("\n");
    sb.append("    outputPath: ").append(toIndentedString(outputPath)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
