/*
 * Radarr
 * The way users should interact with Radarr programatically. To utilize any of these endpoints you will need a few pieces of information:  ex: localhost:7878/api/v3/movies?apiKey={key_here}  * url: localhost, 10.1.0.1, 192.168.1.1, etc * port: 7878 (unless you modify it) * apiKey: Located in Settings > General > Security
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.codemakers.radarr4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * QualityRevision
 */

public class QualityRevision {
  @SerializedName("version")
  private Integer version = null;

  @SerializedName("real")
  private Integer real = null;

  @SerializedName("isRepack")
  private Boolean isRepack = null;

  public QualityRevision version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(required = true, description = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public QualityRevision real(Integer real) {
    this.real = real;
    return this;
  }

   /**
   * Get real
   * @return real
  **/
  @Schema(required = true, description = "")
  public Integer getReal() {
    return real;
  }

  public void setReal(Integer real) {
    this.real = real;
  }

  public QualityRevision isRepack(Boolean isRepack) {
    this.isRepack = isRepack;
    return this;
  }

   /**
   * Get isRepack
   * @return isRepack
  **/
  @Schema(required = true, description = "")
  public Boolean isIsRepack() {
    return isRepack;
  }

  public void setIsRepack(Boolean isRepack) {
    this.isRepack = isRepack;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QualityRevision qualityRevision = (QualityRevision) o;
    return Objects.equals(this.version, qualityRevision.version) &&
        Objects.equals(this.real, qualityRevision.real) &&
        Objects.equals(this.isRepack, qualityRevision.isRepack);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, real, isRepack);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QualityRevision {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    real: ").append(toIndentedString(real)).append("\n");
    sb.append("    isRepack: ").append(toIndentedString(isRepack)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
