/*
 * Radarr
 * The way users should interact with Radarr programatically. To utilize any of these endpoints you will need a few pieces of information:  ex: localhost:7878/api/v3/movies?apiKey={key_here}  * url: localhost, 10.1.0.1, 192.168.1.1, etc * port: 7878 (unless you modify it) * apiKey: Located in Settings > General > Security
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.codemakers.radarr4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.codemakers.radarr4j.model.QualityQuality;
import de.codemakers.radarr4j.model.QualityRevision;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Quality
 */

public class Quality {
  @SerializedName("quality")
  private QualityQuality quality = null;

  @SerializedName("revision")
  private QualityRevision revision = null;

  public Quality quality(QualityQuality quality) {
    this.quality = quality;
    return this;
  }

   /**
   * Get quality
   * @return quality
  **/
  @Schema(required = true, description = "")
  public QualityQuality getQuality() {
    return quality;
  }

  public void setQuality(QualityQuality quality) {
    this.quality = quality;
  }

  public Quality revision(QualityRevision revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision
  **/
  @Schema(required = true, description = "")
  public QualityRevision getRevision() {
    return revision;
  }

  public void setRevision(QualityRevision revision) {
    this.revision = revision;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Quality quality = (Quality) o;
    return Objects.equals(this.quality, quality.quality) &&
        Objects.equals(this.revision, quality.revision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quality, revision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Quality {\n");
    
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
