/*
 * Radarr
 * The way users should interact with Radarr programatically. To utilize any of these endpoints you will need a few pieces of information:  ex: localhost:7878/api/v3/movies?apiKey={key_here}  * url: localhost, 10.1.0.1, 192.168.1.1, etc * port: 7878 (unless you modify it) * apiKey: Located in Settings > General > Security
 *
 * OpenAPI spec version: 3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.codemakers.radarr4j.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * TagDetail
 */

public class TagDetail {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("delayProfileIds")
  private List<Integer> delayProfileIds = null;

  @SerializedName("notificationIds")
  private List<Integer> notificationIds = null;

  @SerializedName("restrictionIds")
  private List<Integer> restrictionIds = null;

  @SerializedName("netImportIds")
  private List<Integer> netImportIds = null;

  @SerializedName("movieIds")
  private List<Integer> movieIds = null;

  public TagDetail id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TagDetail label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public TagDetail delayProfileIds(List<Integer> delayProfileIds) {
    this.delayProfileIds = delayProfileIds;
    return this;
  }

  public TagDetail addDelayProfileIdsItem(Integer delayProfileIdsItem) {
    if (this.delayProfileIds == null) {
      this.delayProfileIds = new ArrayList<>();
    }
    this.delayProfileIds.add(delayProfileIdsItem);
    return this;
  }

   /**
   * Get delayProfileIds
   * @return delayProfileIds
  **/
  @Schema(description = "")
  public List<Integer> getDelayProfileIds() {
    return delayProfileIds;
  }

  public void setDelayProfileIds(List<Integer> delayProfileIds) {
    this.delayProfileIds = delayProfileIds;
  }

  public TagDetail notificationIds(List<Integer> notificationIds) {
    this.notificationIds = notificationIds;
    return this;
  }

  public TagDetail addNotificationIdsItem(Integer notificationIdsItem) {
    if (this.notificationIds == null) {
      this.notificationIds = new ArrayList<>();
    }
    this.notificationIds.add(notificationIdsItem);
    return this;
  }

   /**
   * Get notificationIds
   * @return notificationIds
  **/
  @Schema(description = "")
  public List<Integer> getNotificationIds() {
    return notificationIds;
  }

  public void setNotificationIds(List<Integer> notificationIds) {
    this.notificationIds = notificationIds;
  }

  public TagDetail restrictionIds(List<Integer> restrictionIds) {
    this.restrictionIds = restrictionIds;
    return this;
  }

  public TagDetail addRestrictionIdsItem(Integer restrictionIdsItem) {
    if (this.restrictionIds == null) {
      this.restrictionIds = new ArrayList<>();
    }
    this.restrictionIds.add(restrictionIdsItem);
    return this;
  }

   /**
   * Get restrictionIds
   * @return restrictionIds
  **/
  @Schema(description = "")
  public List<Integer> getRestrictionIds() {
    return restrictionIds;
  }

  public void setRestrictionIds(List<Integer> restrictionIds) {
    this.restrictionIds = restrictionIds;
  }

  public TagDetail netImportIds(List<Integer> netImportIds) {
    this.netImportIds = netImportIds;
    return this;
  }

  public TagDetail addNetImportIdsItem(Integer netImportIdsItem) {
    if (this.netImportIds == null) {
      this.netImportIds = new ArrayList<>();
    }
    this.netImportIds.add(netImportIdsItem);
    return this;
  }

   /**
   * Get netImportIds
   * @return netImportIds
  **/
  @Schema(description = "")
  public List<Integer> getNetImportIds() {
    return netImportIds;
  }

  public void setNetImportIds(List<Integer> netImportIds) {
    this.netImportIds = netImportIds;
  }

  public TagDetail movieIds(List<Integer> movieIds) {
    this.movieIds = movieIds;
    return this;
  }

  public TagDetail addMovieIdsItem(Integer movieIdsItem) {
    if (this.movieIds == null) {
      this.movieIds = new ArrayList<>();
    }
    this.movieIds.add(movieIdsItem);
    return this;
  }

   /**
   * Get movieIds
   * @return movieIds
  **/
  @Schema(description = "")
  public List<Integer> getMovieIds() {
    return movieIds;
  }

  public void setMovieIds(List<Integer> movieIds) {
    this.movieIds = movieIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagDetail tagDetail = (TagDetail) o;
    return Objects.equals(this.id, tagDetail.id) &&
        Objects.equals(this.label, tagDetail.label) &&
        Objects.equals(this.delayProfileIds, tagDetail.delayProfileIds) &&
        Objects.equals(this.notificationIds, tagDetail.notificationIds) &&
        Objects.equals(this.restrictionIds, tagDetail.restrictionIds) &&
        Objects.equals(this.netImportIds, tagDetail.netImportIds) &&
        Objects.equals(this.movieIds, tagDetail.movieIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, delayProfileIds, notificationIds, restrictionIds, netImportIds, movieIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    delayProfileIds: ").append(toIndentedString(delayProfileIds)).append("\n");
    sb.append("    notificationIds: ").append(toIndentedString(notificationIds)).append("\n");
    sb.append("    restrictionIds: ").append(toIndentedString(restrictionIds)).append("\n");
    sb.append("    netImportIds: ").append(toIndentedString(netImportIds)).append("\n");
    sb.append("    movieIds: ").append(toIndentedString(movieIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
